<?php
require_once __DIR__ . '/../../admin_auth.php';
use App\Repositories\MatriculaRepository;
use App\Repositories\CertificadoRepository;
$id=(int)($_GET['id']??0); $mat=(new MatriculaRepository(db()))->find($id); if(!$mat){http_response_code(404);exit('Matrícula no encontrada.');}
$cert=(new CertificadoRepository(db()))->findByMatricula($id); if($cert){flash('info','Certificado existente','Esta matrícula ya tiene un certificado.'); header('Location: ' . app_url('/admin/matriculas/show.php') . '?id=' . $id); exit;}
$ps=payment_status((float)$mat['precio_total'],(float)$mat['pagado']); $pageTitle='Emitir certificado'; include __DIR__.'/../layouts/header.php'; include __DIR__.'/../layouts/nav.php';
?>
<main class="container pb-5"><div class="card p-4 mx-auto" style="max-width:950px"><div class="d-flex justify-content-between mb-4"><div><h3 class="fw-bold mb-1">Emitir certificado</h3><div class="text-muted"><?=e($mat['nombre'].' '.$mat['apellido'])?> · <?=e($mat['curso'])?></div></div><a href="<?=e(app_url('/admin/matriculas/show.php'))?>?id=<?=$id?>" class="btn btn-outline-secondary">Cancelar</a></div><?php if($ps['key']!=='pagado'): ?><div class="alert alert-warning"><strong>No se puede emitir todavía.</strong> La matrícula debe estar totalmente pagada. Estado actual: <?=$ps['label']?>.</div><?php else: ?><form method="post" action="<?=e(app_url('/actions/certificados/store.php'))?>"><input type="hidden" name="id_matricula" value="<?=$id?>"><div class="row g-3"><div class="col-md-4"><label class="form-label">Fecha inicio</label><input type="date" name="fecha_inicio" class="form-control" required></div><div class="col-md-4"><label class="form-label">Fecha fin</label><input type="date" name="fecha_fin" class="form-control" required></div><div class="col-md-4"><label class="form-label">Horas académicas</label><input type="number" name="horas" class="form-control" min="1" required></div><div class="col-md-6"><label class="form-label">Ponente</label><select name="docente" class="form-select" required><option value="RONALD HUERTA AVALOS">RONALD HUERTA ÁVALOS</option><option value="YSABEL TORRES TARAZONA">YSABEL TORRES TARAZONA</option><option value="RONALD HUERTA AVALOS E YSABEL TORRES TARAZONA">RONALD HUERTA ÁVALOS E YSABEL TORRES TARAZONA</option></select></div><div class="col-md-3"><label class="form-label">Modalidad</label><select name="modalidad" class="form-select"><option>PRESENCIAL</option><option>VIRTUAL</option><option>HIBRIDO</option></select></div><div class="col-md-3"><label class="form-label">Nota final</label><input type="number" name="nota" class="form-control" step="0.01" min="0" max="20"></div><div class="col-12"><label class="form-label">Observaciones</label><textarea name="observaciones" rows="3" class="form-control"></textarea></div></div><div class="text-end mt-4"><button class="btn btn-warning btn-lg"><i class="fa-solid fa-certificate me-1"></i> Emitir certificado</button></div></form><?php endif; ?></div></main><?php include __DIR__.'/../layouts/footer.php'; ?>
