<?php
require_once __DIR__ . '/../../admin_auth.php';
use Dompdf\Dompdf; use Dompdf\Options; use App\Repositories\MatriculaRepository;
$id=(int)($_GET['id']??0); $repo=new MatriculaRepository(db()); $m=$repo->find($id); if(!$m)exit('Matrícula no encontrada.'); $payments=$repo->payments($id);
function img64(string $path): string { if(!is_file($path))return ''; $mime=mime_content_type($path)?:'image/png'; return 'data:'.$mime.';base64,'.base64_encode(file_get_contents($path)); }
$logo=img64(__DIR__.'/../../assets/img/logo.png'); $clinic=img64(__DIR__.'/../../assets/img/logo_clinica.png'); $firma=img64(__DIR__.'/../../assets/img/firma_huerta.png'); $precio=(float)$m['precio_total'];$pagado=(float)$m['pagado'];$saldo=max(0,$precio-$pagado);
$rows=''; foreach($payments as $p){$rows.='<tr><td>'.e(date('d/m/Y',strtotime($p['fecha']))).'</td><td>'.e($p['metodo_pago']).'</td><td>'.e($p['numero_operacion']?:'-').'</td><td>'.e($p['observacion']?:'-').'</td><td class="money">'.money($p['monto']).'</td></tr>';} if(!$rows)$rows='<tr><td colspan="5" class="center">No se han registrado pagos.</td></tr>';
$html='<!doctype html><html lang="es"><head><meta charset="utf-8"><style>@page{margin:28px 38px}body{font-family:DejaVu Sans,sans-serif;color:#25364d;font-size:10px}.head{text-align:center;border-bottom:2px solid #19b5c8;padding-bottom:8px}.logos img{height:58px;margin:0 12px}.brand{font-size:15px;font-weight:bold;color:#2a2c78}.title{text-align:center;font-size:20px;font-weight:bold;letter-spacing:3px;margin:12px}.section{background:#2a2c78;color:#fff;padding:6px 9px;font-weight:bold;margin-top:9px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #d8dfe6;padding:6px}th{background:#eef4fa;text-align:left}.label{width:28%;font-weight:bold;background:#f1f6fb}.money{text-align:right;font-weight:bold}.center{text-align:center;color:#777}.summary td{padding:7px}.firma{text-align:center;margin-top:25px}.firma img{height:55px}.line{width:210px;border-top:1px solid #222;margin:auto}.footer{position:fixed;bottom:-15px;left:0;right:0;text-align:center;font-size:7px;color:#777}</style></head><body><div class="head"><div class="logos">'.($logo?'<img src="'.$logo.'">':'').($clinic?'<img src="'.$clinic.'">':'').'</div><div class="brand">CAPACITACIONES MÉDICAS BAHÍA</div><div>Formación y capacitación académica</div></div><div style="text-align:right;font-size:8px;margin-top:5px">Código de matrícula: <strong>MAT-'.str_pad($id,6,'0',STR_PAD_LEFT).'</strong></div><div class="title">FICHA DE MATRÍCULA</div><div class="section">DATOS DEL MATRICULADO</div><table><tr><td class="label">Nombres y apellidos</td><td>'.e($m['nombre'].' '.$m['apellido']).'</td></tr><tr><td class="label">DNI</td><td>'.e($m['dni']).'</td></tr><tr><td class="label">Teléfono</td><td>'.e($m['telefono']).'</td></tr><tr><td class="label">Correo electrónico</td><td>'.e($m['correo']).'</td></tr></table><div class="section">DATOS DE LA MATRÍCULA</div><table><tr><td class="label">Curso</td><td><strong>'.e($m['curso']).'</strong></td></tr><tr><td class="label">Fecha de matrícula</td><td>'.e(date('d/m/Y',strtotime($m['fecha']))).'</td></tr><tr><td class="label">Precio acordado</td><td><strong>'.money($precio).'</strong></td></tr></table><div class="section">HISTORIAL DE PAGOS</div><table><thead><tr><th>Fecha</th><th>Método</th><th>Operación</th><th>Observación</th><th>Monto</th></tr></thead><tbody>'.$rows.'</tbody></table><div class="section">RESUMEN</div><table class="summary"><tr><td>Precio acordado</td><td class="money">'.money($precio).'</td></tr><tr><td>Total pagado</td><td class="money">'.money($pagado).'</td></tr><tr><td><strong>Saldo pendiente</strong></td><td class="money"><strong>'.money($saldo).'</strong></td></tr></table><div class="firma">'.($firma?'<img src="'.$firma.'"><br>':'').'<div class="line"></div><strong>Dr. Ronald Huerta Ávalos</strong><br>Especialista en Radiología y Anestesiología<br>Director de Capacitaciones Médicas Bahía</div><div class="footer">Capacitaciones Médicas Bahía — Ficha de Matrícula — '.date('d/m/Y H:i').'</div></body></html>';
$options=new Options();$options->set('defaultFont','DejaVu Sans');$dompdf=new Dompdf($options);$dompdf->loadHtml($html);$dompdf->setPaper('A4','portrait');$dompdf->render();while(ob_get_level())ob_end_clean();header('Content-Type: application/pdf');header('Content-Disposition: inline; filename="Ficha-Matricula-MAT-'.str_pad($id,6,'0',STR_PAD_LEFT).'.pdf"');echo $dompdf->output();exit;
