<?php
require_once __DIR__ . '/../../admin_auth.php';
use App\Repositories\MatriculaRepository;
$id=(int)($_GET['id']??0); $repo=new MatriculaRepository(db()); $mat=$repo->find($id); if(!$mat){http_response_code(404);exit('Matrícula no encontrada.');}
$saldo=max(0,(float)$mat['precio_total']-(float)$mat['pagado']); if((float)$mat['precio_total']<=0){ header('Location: ' . app_url('/admin/matriculas/price.php') . '?id=' . $id); exit; } $can=$saldo>0;
if(!$can){flash('info','Matrícula pagada','Esta matrícula no tiene saldo pendiente.'); header('Location: ' . app_url('/admin/matriculas/show.php') . '?id=' . $id); exit;}
$pageTitle='Registrar pago'; include __DIR__.'/../layouts/header.php'; include __DIR__.'/../layouts/nav.php';
?>
<main class="container pb-5"><div class="card p-4 mx-auto" style="max-width:850px"><div class="d-flex justify-content-between align-items-start mb-4"><div><h3 class="fw-bold mb-1">Registrar pago</h3><div class="text-muted"><?=e($mat['nombre'].' '.$mat['apellido'])?> · <?=e($mat['curso'])?></div></div><a class="btn btn-outline-secondary" href="<?=e(app_url('/admin/matriculas/show.php'))?>?id=<?=$id?>">Cancelar</a></div><div class="row g-3 mb-4"><div class="col-md-4"><div class="p-3 bg-light rounded"><small>Precio</small><div class="fw-bold"><?=money($mat['precio_total'])?></div></div></div><div class="col-md-4"><div class="p-3 bg-light rounded"><small>Pagado</small><div class="fw-bold text-success"><?=money($mat['pagado'])?></div></div></div><div class="col-md-4"><div class="p-3 bg-light rounded"><small>Saldo</small><div class="fw-bold text-danger"><?=money($saldo)?></div></div></div></div><form method="post" action="<?=e(app_url('/actions/pagos/store.php'))?>"><input type="hidden" name="id_matricula" value="<?=$id?>"><div class="row g-3"><div class="col-md-4"><label class="form-label">Fecha</label><input type="date" name="fecha" class="form-control" value="<?=date('Y-m-d')?>" required></div><div class="col-md-4"><label class="form-label">Monto</label><input type="number" name="monto" class="form-control" min="0.01" max="<?=e(number_format($saldo,2,'.',''))?>" step="0.01" required></div><div class="col-md-4"><label class="form-label">Método</label><select name="metodo_pago" class="form-select"><option>Efectivo</option><option>Yape</option><option>Transferencia</option><option>Tarjeta</option></select></div><div class="col-md-6"><label class="form-label">N.º de operación</label><input name="numero_operacion" class="form-control" maxlength="100"></div><div class="col-md-6"><label class="form-label">Observación</label><input name="observacion" class="form-control"></div></div><div class="text-end mt-4"><button class="btn btn-success btn-lg"><i class="fa-solid fa-floppy-disk me-1"></i> Guardar pago</button></div></form></div></main><?php include __DIR__.'/../layouts/footer.php'; ?>
